[env:esp32dev]
platform = espressif32@5.3.0    ; Phiên bản Core 2.0.5 ổn định nhất cho FabGL
board = esp32dev
framework = arduino

; Chỉ định vùng chứa file .h của các đĩa giả lập
build_flags = 
    -Isrc/disks
    -Isrc/minidisks
    -D CORE_DEBUG_LEVEL=0

monitor_speed = 115200

lib_deps =
    fdivitto/FabGL @ ^1.0.9